denisenkom/go-mssqldb

- tds.go
@dimdin can you kindly look at this pull request, this should fix Issue #69
> Fixed bug #69

- mssql.go
A fix for the issue experienced in #81. When the connection to the SQLServer returns an i/o timeout indicating that the connection to the database is in a bad state it now returns `driver.ErrBadConn` which enables the SQL logic to generate a new connection.
Modified `CheckBadConn(err)` to return `driver.ErrBadConn` on a timeout
Use `CheckBadConn` on the Query/Exec methods if they aren't part of a transaction
> #81 Treating timeouts as the connection being in a bad state

- token.go
> Ignore unknown env change types Issue #73

- tds.go
When opening a connection to an availability group listener, DNS gives back a list of IP addresses.  One of them will work, and the rest timeout when you try to dial them.  If you try to dial them sequentially and you are unlucky in the ordering, then establishing a connection might take a while.  Better to try them all at once, and proceed as soon as one of them works.
Ref issue #86 
P.S.  Massive thanks to @mjibson for blazing the trail here!
> Improve performance of opening connections to Availability Group Listeners

- examples/simple.go
changed main() to simplemain() inside simple.go file
> declared main func 2 times in same package

- mssql.go
- mssql_go18.go
- queries_go18_test.go
- tran.go
> Implemented Context methods and transaction Isolation levels

- mssql.go
- parser.go
- parser_test.go
- queries_go18_test.go
> implemented named parameters

- mssql_go18.go
- queries_go18_test.go
> Implement driver.Pinger interface

- buf.go
- mssql.go
- mssql_go18.go
- net.go
- queries_go18_test.go
- queries_test.go
- tds.go
- tds_test.go
- token.go
@kardianos please take a look.
All tests are passing.  But code looks ugly.  Maybe you would have some ideas on how to make it better.   I think if there is a way to integrate Context with network sockets then it would probably allow to simplify some of this logic.
> Cancelable queries

- README.md
- tds.go
- tds_test.go
> Support for parsing connection strings in ODBC and URL formats

- mssql.go
- mssql_go1.3.go
- mssql_go1.3pre.go
- queries_go18_test.go
- queries_test.go
- tds.go
- token.go
Test disconnect connditions. Refactor token processing to
ensure correctness.
Fixes #200
> support pluggable dialers for testing

- appveyor.yml
This address #194 and #229 
This config will build the code and run the tests on multiple versions of Go and sql server.
> CI with appveyor

- buf.go
- bulkcopy.go
- mssql.go
- token.go
do not reuse conn after timeout err occurred
fix #119 though its closed
> fix timeout issue

- buf.go
- bulkcopy_test.go
- mssql.go
- queries_test.go
> Better error reporting

- bulkcopy.go
- bulkcopy_test.go
Fixed convert big datetime in bulkcopy like "Jan 1 4010"
> Fix: big datetime in bulkcopy

- queries_go18_test.go
- queries_go19_test.go
- queries_test.go
Also fix panics when a bad connection string is used.
> tests: fix go vet errors, making go1.10 test happy

- bulkcopy.go
- bulkcopy_sql.go
- bulkcopy_test.go
- examples/bulk/bulk.go
- mssql.go
- mssql_go18.go
- mssql_go19.go
- mssql_go19pre.go
- queries_go18_test.go
- queries_test.go
Use alias for compatibilit for now.
> mssql: rename structs to prevent stutter

- appveyor.yml
- bulkcopy.go
- bulkcopy_sql.go
- bulkcopy_test.go
- mssql.go
- mssql_go18.go
> mssql: fix data race in bulk insert

- README.md
- appveyor.yml
- mssql.go
- mssql_go19.go
- queries_go110_test.go
- types.go
> add date time specific parameter types

- mssql.go
- mssql_go19.go
- queries_go19_test.go
> Fix for OUTPUT parameters of DateTime type

- bulkcopy.go
- bulkcopy_test.go
- mssql.go
- mssql_go19.go
- queries_go19_test.go
- queries_test.go
- types.go
And refactor date handling to reduce code duplication
> Clip date to valid range

- README.md
- mssql.go
- mssql_go19.go
- queries_go110_test.go
- queries_go19_test.go
- token.go
> mssql: allow returning return status code

- doc/how-to-use-newconnector.md
Align with what the example is using.
> Import the drive as 'mssql' instead of 'mssqldb'

- README.md
- queries_go19_test.go
Documentation and test for #378
> Add documentation and test for reading output parameters from a stored procedure with resultset

- tds_test.go
Added E2E test verifying fix in PR #483 (issue #450)
> Added test for SSPI authentication

- go.mod
xref: https://github.com/golang/go/issues/30446#issuecomment-468028807
> Support go mod with Go 1.11

- README.md
- conn_str.go
- conn_str_test.go
- doc/how-to-use-applicatinintent-connection-property.md
> Errors out when applicationintent is specified without database

- go.mod
- ntlm.go
- ntlm_test.go
Fix for https://github.com/denisenkom/go-mssqldb/issues/146
> Add support for NTLMv2

- tvp_go19.go
- tvp_go19_db_test.go
#563 fix issue
standard golang package https://golang.org/pkg/database/sql/
* [sql.NullBool](https://golang.org/pkg/database/sql/#NullBool)
* [sql.NullFloat64](https://golang.org/pkg/database/sql/#NullFloat64)
* [sql.NullInt64](https://golang.org/pkg/database/sql/#NullInt64)
* [sql.NullString](https://golang.org/pkg/database/sql/#NullString)
> Added support for standard golang types from pkg sql

- bulkcopy_test.go
- types.go
> Empty Strings Instead Of Nulls Using Bulk.

- mssql.go
> mssql: support IsValid for the driver Validator interface

- queries_test.go
- types.go
- types_test.go
binary(x) is a variable size type, not fixed size. #685
> fix size reporting for typeBigBinary
