tds.go
tds_test.go

This fixes #87 where the `keepAlive` parameter was being ignored.

Fix keepAlive parameter

---

mssql.go

The `token` contains the error in the `Query` and `Exec` methods not `err`

Fixed errors within transactions

---

mssql.go

As the transaction hasn't started yet it, we check to see if it is already in a transaction (if it is return a normal error), then that the error is either a timeout or a non-temporary network error, we should be safe to return `driver.ErrBadConn` at this point

Added `CheckBadConn` on the `Begin` method of a transaction.

---

mssql_go1.3.go
mssql_go1.3pre.go
tds.go

This make the library compile with go <= 1.2

Conditionally compile with net.Dialer.KeepAlive option if go >= 1.3

---

token.go

[ENVCHANGE spec](https://msdn.microsoft.com/en-us/library/dd303449.aspx)
13: Database Mirroring Partner, PARTNER_NODE = B_VARCHAR, NEWVALUE = PARTNER_NODE
This env can't be ignored via readBVarByte

ignore DatabaseMirrorPartner

---

tds.go

The below MSDN article describes the correct behavior for AlwaysOn
Availability Groups, which is to try all IP addresses until a connection
request succeeds or until the connection requests time out.
https://msdn.microsoft.com/en-us/library/hh213417.aspx#AGlisteners
fixes #86

Attempt all available IP addresses for host

---

mssql.go

Previously, connection string parsing failing to trim extraneous whitespace surrounding either names or values.  Hence, if a connection string looked like this:
`"server=my_server; database=my_database; user id=me"`
Then the following key/value pairs would be put into the hash map:
`"server":"my_server"`
`" database":"my_database"`
`" user id":"me"`
Note the extra space in front of "database" and "user id".  This is a problem because the parseConnectionParams() function in tds.go tries to pull out key/value pairs by name.  For example, it does the following:
`p.database = params["database"]`
This will fail to pull out the " database" key that we put into the map, because it assumes that there is no leading or trailing whitespace around the key.
The single commit included in this pull …

Fix connection string parsing

---

types.go

hey there, I noticed an issue where often I would receive the same value in a column for two sequential rows when using rows.Next().  This is caused by slicing a buffer, which ends up reusing the backing array.  This happens every time on my binary(32) column, but making a copy like below fixes it.

fix an issue where col data can be overwritten during Next()

---

tds.go

When cross-compiling, net.LookupIP will use the built-in Go resolver,
which will not correctly resolve hosts values that are IPs. Handle this
case by checking whether the host is an IP if resolution fails.
Note that this looks like it will be handled by net.LookupIP in Go 1.5, but until then, this patch is needed to allow hosts to be specified as an IP address when using a cross-compiled binary.
More information can be found in
* https://groups.google.com/forum/#!topic/golang-nuts/nVqoIKHdZ6s/discussion.
* https://github.com/golang/go/issues/11335
* https://go-review.googlesource.com/#/c/11420/
This also fixes the issue discussed in #102.

try parsing host as IP if resolution fails

---

README.md
mssql.go
tds.go
token.go

Add support for database mirroring sessions.
Add two new connection string parameters, `failoverpartner` and `failoverport`. These new parameters are only used if a partner hasn't already been associated with the connection string.
Similarly to how the Microsoft drivers work, cache the partner of the first successful connection that provides a partner token. (see https://msdn.microsoft.com/en-us/library/ms175484.aspx#InitialConnection)
When a connection to the intial server fails, try the cached partner. If a partner has not yet been cached, use the `failoverpartner` and `failoverport` values.
The database mirror partner values provided in the ENVCHANGE token do not include port information, so append an instance name to the partner name before caching the partner so connecting to the …

add support for database mirroring sessions

---

tds.go

Hi,
Thanks so much for the work on this package, it's great!
When using it on an insert intensive workload, I noticed that the Go process was completely CPU bound.  Profiling, it looked like a major culprit was str2ucs2, transcoding the string parameters to UTF-16 for binding into the queries.  I only had a couple of VARCHAR columns (along with a couple dozen ints and datetimes) and they were only ten characters each, so this was pretty alarming.
As an experiment, I've re-implemented srt2ucs2 to essentially unroll the functionality from the bytes and encoding/binary packages.  This has substantially improved performance on my workload.  The process is no longer CPU bound and re-profiling and shown the CPU usage of str2ucs2 to be much lower. Inserts with more or bigger string parameters …

Improve performance of str2ucs2

---

README.md
mssql.go
tds.go
token.go

OK, I've taken a crack at this as discussed in issue #127.  I've tested it in all the ways that I can with our database infrastructure and it seems to work fine.
Apologies in advance for the use of another `goto` but it seemed like the best way to implement the connection state logic without a major refactoring.
Please let me know if there are any suggestions for improvements.

Support for ReadOnly connections to Availability Groups

---

tds.go

While re-using this code in another application I realised that there is a potential bug.  It might be possible for one IP address to return an error before another one returns a successful connection, in which case the error handling code would have caused the connection to be ignored.  This never happened to occur in the availability group because the non-primary listeners would take a while to time out.  Don't want to depend on that, though.

Fix potential race condition bug

---

tds.go

There was a race condition in the dialConnection with multiple machines. If we received an error before we received a connection we would return both a connection and an error. The calling code in mssql.go would then assume we'd failed based on the presence of the error. This change nils out the error if we've obtained a successful connection.

Remove any accumulated errors, otherwise Open will assume we've failed

---

tds.go

Running this code with the data race detector enabled results in a report because we're reading p.port on line 830 and writing to it on line 1026 in different goroutines. There's no way for these to overlap because we're waiting for all the goroutines to finish before we return from dialConnection but the race detector obviously can't tell this.

Hoist port stringing to fix data race report

---

mssql.go
mssql_test.go

Fixes running queries against a sql server that is restarted after
calling db.Open.
Previously, opening a connection and successfully executing queries followed by restarting SQL Server would cause all future queries to fail, because the error would be a `net.OpError` where `Temporary()` returns true and `Timeout()` returns false. Assuming this code scenario used to work as expected, I suspect that the change introduced in https://github.com/golang/go/commit/055ecb7be5805e07498488c59c6f01644fdacccc#diff-ae34eb42831ffecf011ea43c6429582c may have been the root cause of this change in behavior.

return driver.ErrBadConn on all net.Error values

---

README.md
mssql.go

Remove the partnersCache, and instead rely only on the failoverpartner
value from the connection string. This simplifies the code and fixes
issues with creating new connections to the database where the principle server was the value specified in the failover parameter (e.g. An initial connection could not be
made to the instance specified in the server parameter).

Rely only on connection string for failover partners

---

error.go
error_example_test.go

Sometimes it is handy to be able to check details of the error returned from SQL server. Examples of error conditions that may warrant special handling include:
- Deadlock
- Duplicate key in unique index
- Timeout
There may be more.
Although it is possible to attempt to cast a returned error to the `mssql.Error` type, this requires importing the package in the code. While this is not a problem in many cases, it can be a problem with code that is designed to work with a number of different database backends.
A simpler approach to error handling is to provide methods on the `Error` type that will return information. A calling program can then attempt to cast the error type to a local interface type.
This example shows how a calling program can check for a SQL Server deadlock error without …

Add SQLError... methods to Error type

---

mssql.go

I believe this doesn't necessary close #134 or #105 but I think it will help troubleshoot in the future and addresses problems that were brought up in both issue threads.
net.Error has a method .Timeout() that returns a bool if the error was because of an expired timeout. I added a check before the return of the driver.ErrBadConn.

added a check to net.Error.Timeout() before returning driver.ErrBadConn

---

log.go
mssql.go
tds.go

Previously the driver would only accept setting the logger to stdlib
*log.Logger structs. This change allows anything with a logger-like
interface to be used instead.
In order to make logging work even when a logger isn't explicitly
specified, an optionalLogger struct has been added that still works (by
logging to the global stdlib logger) as its zero value. It fills the
same function as the Logger struct it's replacing, though the naming
makes things a little more obvious.
Another option I explored was just using the new Logger interface
directly as the type of log in MssqlDriver. We could provide a default
struct that implements Logger and just forwards to the global stdlib log
functions
The problem was that this default needed to be provided everywhere a
MssqlDriver is created. Since …

Use interface for logging

---

mssql_go18.go
queries_go18_test.go

mssql: update to latest go1.8 BeginTx

---

queries_test.go
types.go
uniqueidentifier.go
uniqueidentifier_test.go

SQL Server's UniqueIdentifier type uses native endianness for some of
its fields within the UUID. Add a new type, UniqueIdentifier, that
correctly handles scanning based on the type of data being scanned.
Scanning a []byte swaps the bytes of the fields that SQL Server stores
using native endianness.
Scanning a string decodes the hex-encoded values without swapping any
bytes.
Implement fmt.Stringer so that the returned value of String is congruent
with the behavior of CAST(myuniqueidentifer AS varchar(36)).

add UniqueIdentifier type

---

README.md
doc.go
mssql.go
mssql_test.go
queries_go18_test.go
queries_test.go
tds.go
tds_test.go
tran.go

There exists many queries today that uses native "@" placeholders
for queries. Parsing queries today is not perfect and introduces
more work that isn't always needed. Introduce a new driver type
that when used will not preprocess any queries.
Fixes #199

mssql: add new driver type w/o pre-processing query

---

mssql.go

When a given Exec call contains multiple SQL statement, we should sum the number of rows affected from all the statements executed rather than using the number of rows affected from the last statement, e.g.
```
UPDATE Timer SET unit = 1 WHERE id = 1234 # no rows affect if the row doesn't exit, otherwise 1 row affected
INSERT INTO Timer (id, unit)
SELECT 1234, 1
FROM Timers
WHERE @@rowcount = 0 # if the above statement affects rows, this will return no rows affected
```
By summing all the rows affected in the Go code, you get the count of what happened.

Sum rows affected for multi-statement Exec calls.

---

bulkcopy.go

I send patch to fix bulk.go compile errors below:
```
./bulkcopy.go:171: cannot use tokenRow (type token) as type byte in argument to buf.WriteByte
./bulkcopy.go:205: cannot use tokenDone (type token) as type byte in argument to buf.WriteByte
./bulkcopy.go:240: cannot use tokenColMetadata (type token) as type byte in argument to buf.WriteByte
```

Fix bulkcopy.go compile errors

---

tds.go
token.go

ENVCHANGE data can send a 0 byte length BVarChar. SqlCollation is a perfect example of this:
227 8 0 7 5 9 4 16 32 0 0
The above when being parsed will cause an io.EOF error and is sent every time you connect to Azure SQL Data Warehouse (SQLDW).
Modified readBVarChar to cater for this, plus additional modifications to the SqlCollation parsing to be in accordance with the specification and ready for future changes.

Modified to cater for 0 byte length BVarChars. Fixing an unwanted io.EOF error.

---

bulkcopy.go
bulkcopy_sql.go
bulkcopy_test.go
decimal.go
mssql_go18.go
types.go

decimal types first pass. money types should be the same, but not working for some reason. Submitting decimal types only this time
Reference: https://github.com/Microsoft/mssql-jdbc/blob/master/src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java#L3307

bulk copy for decimal types

---

bulkcopy.go
bulkcopy_test.go
decimal_test.go
mssql.go
mssql_go19.go
mssql_go19pre.go
mssql_test.go
parser.go
queries_go19_test.go
queries_test.go
tds.go
tds_go18_test.go
tds_test.go
token.go
types_test.go

In go1.9 expect NamedValueChecker to land. Support OUTPUT
parameters and model how other types can be supported.

mssql: support OUTPUT parameters, detect PROC names

---

buf.go
mssql.go
queries_go18_test.go
queries_test.go
tds.go
token.go

Also set the connectionGood = false so next time it hits the driver,
it can remove the connection from the pool.
This prevents certain queries with errors being executed more then once.

mssql: do not directly return driver.ErrBadConn, return actual error

---

types.go
types_test.go

Fixes #298 
Add missing typeInt1 and typeInt2 into the typeInfo switches to avoid panic on *rows.ColumnTypes() call when these column types are returned from the server.

Add support for typeInt1 and typeInt2 in switch statements

---

buf.go
buf_test.go
mssql.go
queries_go19_test.go
tds.go

If the packet size is set too small, the read buffer size will
overflow. Prevent this by setting the buffer size independent of the
packet size.
For #166

mssql: de-couple the packet size from the buffer size

---

queries_go19_test.go
tds.go

This is what I found regarding https://github.com/denisenkom/go-mssqldb/issues/166:
Microsoft Message Analyzer shows that Go tls uses heuristic algorithm to determine TLS payload size, which produces splitting multiple TCP segments for for large TDS packets of SQL queries over 2326 bytes, while SQL Server seems to expect one TCP segment per TDS packet.
Disabling the algorithm mentioned above (could be found in Conn.maxPayloadSizeForWrite of crypto/tls package) fixes the issue.

fix #166: Azure SQL long query: driver: bad connection

---

types.go
types_test.go

I found two more column data types that weren't fully supported in the makeGoLangScanType func and associated switch statements, which result in panics.
SMALLDATETIME NOT NULL and DATETIME NOT NULL

Add support for typeDateTim4 and typeDateTime in switch statements

---

types.go
types_test.go

Given a database table:
create table test_table(m money not null)
the statements
rows, _ := db.Query("SELECT * FROM test_table6")
cols, _ := rows.ColumnTypes()
panic with:
panic: not implemented makeDecl for type 60
goroutine 1 [running]:
github.com/denisenkom/go-mssqldb.makeGoLangScanType(0x3c, 0x8, 0x0, 0xc42001ee30, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, ...)
/home/paul/gocode/src/github.com/denisenkom/go-mssqldb/types.go:976 +0x1359
github.com/denisenkom/go-mssqldb.(*MssqlRows).ColumnTypeScanType(0xc420082870, 0x0, 0xc420082870, 0x7f977af93188)
/home/paul/gocode/src/github.com/denisenkom/go-mssqldb/mssql.go:586 +0x73
database/sql.rowsColumnInfoSetup(0x7f8000, 0xc420082870, 0xc4200da4b0, 0x5d6843, 0xc420299ec0)
/usr/local/go/src/database/sql/sql.go:2641 +0x17b
because `makeGoLangScanType` and …

Fix `rows.ColumnTypes()`  for money not null type

---

batch/batch_test.go
bulkcopy.go

I maintain the Fedora package of go-mssqldb, and the recent update to go 1.10 (slated to appear in Fedora 28) triggered a couple of test failures due to `go vet` being [run by default now](https://golang.org/doc/go1.10#test). It looks like you'd already made an earlier pass for this a few commits back; this patch just grabs a couple of stragglers.

Fix tests for Go 1.10

---

buf.go
buf_test.go
bulkcopy.go
bulkcopy_test.go
mssql.go
mssql_go110.go
net.go
rpc.go
tds.go
tds_test.go
tran.go

The bulk table load uses a per-session temp table. Pull
out a single connection to fix the test.
Fixes #329

mssql: support the connection session resetter interface

---

README.md
tds.go

I think we should not use a connection time default. This has confused many people. I'm not even sure the setting means the same thing in SQL Server driver. In this driver it sets the response deadline after a packet has been set, effectively setting the query timeout.

mssql: default to no connection time, use context.Context

---

mssql_go19.go
mssql_go19pre.go
queries_go19_test.go
token.go

queries: use reflect to support other in-out value types

---

buf.go
buf_test.go

Fix for #370:
There are cases when we sequentially call buf.Write, buf.WriteByte, buf.Write. In some of such cases buf.WriteByte doesn't Flush which leads to panic about "slice bounds out of range" on following buf.Write:
1. buf.Write before: (wpos: 3666, packetSize:4096, data len: 430) after: (wpos: 4096, packetSize:4096)
2. buf.WriteByte before: (wpos: 4096, packetSize:4096) after: (wpos: 4097, packetSize:4096)
3. buf.Write: before: (wpos: **4097**, packetSize:4096, data len: 2)
Above the second call of buf.Write will try to slice wbuf with [4097:4096] which produces the panic.

fix #370: bulkcopy: slice bounds out of range

---

bulkcopy_sql.go

Hello,
Ran into this error message the other day: `errCopyInClosed` and was confused by the message. It was unclear at first glance what the message meant base on the style of the message. It is unlike other messages that follow an all lowercase sentence style.
This led us to the source code to find out if `errCopyInClosed` was supposed to be an error variable with the real message as string and it was printing incorrectly.
My proposition is to make the error look like `copyin query is closed` to follow the style of existing errors like [this line](https://github.com/denisenkom/go-mssqldb/blob/8fac8b954edb5b2b4ade733422de37ced41823c8/mssql_go19.go#L75) and other lines like it.
Thanks,
Travis

update error message in bulkcopy_sql.go

---

README.md

We spent a good day debugging what was to us (without knowledge of driver internals) totally unexpected behaviour.
Adding this documentation will prevent others from doing the same mistake. This may be considered a fix for #436.

README: Explain how to use local temporary tables

---

README.md
examples/tvp/tvp.go
mssql_go19.go
tvp_go19.go
tvp_go19_db_test.go
tvp_go19_test.go
types.go

#458 refactoring
Renamed fields.
Removed unused fields.
```
type TVP struct {
//TypeName mustn't be default value
TypeName string
//Value must be the slice, mustn't be nil
Value interface{}
}
```

mssql.TVP refactoring

---

tvp_go19.go
tvp_go19_db_test.go

Fix `Parameter Data type 0x26 has an invalid data length or metadata length`.
When struct field type is *int and value is nil
Add support into `encode`.

Fix "Parameter Data type 0x26 has an invalid data length or metadata length" for type *int

---

mssql.go
tds.go

This fixes error in SSPI authetication handshake which caused that user was immediately logged out after login in. This later resulted in error during sending SQL batch:
`failed to send SQL Batch: write tcp 127.0.0.1:5542->127.0.0.1:1433: wsasend: An existing connection was forcibly closed by the remote host.`
Reported in #475, and also mentioned in #450.
Fix was done by:
- Skipping sending empty sspi messages
- Continue login message loop even we don't have a sspi message  
Fix was verified for both SQL Authentication and Windows Authentication with SQL Server 2016 Standard.

SSPI authentication problem with SQL Server 2016

---

examples/tsql/tsql.go

Moves the `defer db.Close()` to before `db.Ping()`.
Addresses issue #476

Move defer Close to before ping in tsql example

---

tds.go

Upon connection, when the server respond with a rerouted server, the driver change the `p.host` to the `routedServer` and the `p.port` to the `routedPort`. However, the `hostInCertificate` is not updated.
When encrypt is true and trustservercertificate is false, the driver tries to validate the server certificate. This fails if `hostInCertificate` was not updated to the `routedServer` since there is a mismatch between the server certificate being validated (i.e., the certificate in the rerouted server) and the host name the driver provides to be used during certificate validation (i.e., the original server the client wants to connect to).
This change makes sure the `hostInCertificate` is updated when the server respond with a rerouted server, but ONLY IF the client did not provide the …

Update hostInCertificate when server respond with routed server

---

mssql.go
queries_go19_test.go

When calling a stored procedure and the parameter names are not provided, then driver by default sets the parameter names to @p1, @p2, @p3, etc. Unlike executing a parameterized query, this is only useful in rare cases where the stored procedure was created with parameter names that follows the same convention (e.g., `CREATE PROCEDURE insertcusttable @p1 int, @p2 nvarchar(2000) AS BEGIN INSERT INTO customer VALUES(@p1, @p2)`). If the parameter names in the stored procedure do not follow the same convention (e.g., `@id` and `@custname`), then having the driver setting the param names to `@p1` and `@p2` will result in a failure.
This fix changes this behaviour, if the query being executed is a stored procedure and parameter names are not provided, do not set the param names to @p1, @p2, …

Do not set param names to @pn when executing store procedure

---

internal/querytext/parser.go
internal/querytext/parser_test.go
mssql.go

Prior to v1, we should remove the query pre-parser from the main driver.
Also prior to v1, we can create a new Connector that does the processing.

internal/querytext: new package that extracts the parameter parser

---

bulkcopy_test.go
types.go
types_test.go

Fixed the incorrect `varchar(max)` size in [types.go](https://github.com/denisenkom/go-mssqldb/blob/master/types.go#L1189) and made the size checks for `nvarchar` and `varbinary` in line with [`makeGoLangTypeLength()`](https://github.com/denisenkom/go-mssqldb/blob/master/types.go#L1437). In addition I added a unit test to make sure these types return the correct type corresponding to their size. I also modified the bulk insert test to check that these cases are inserted without truncation or error.
Fixes #497

Varchar sizefix

---

tds.go

The `dial_timeout` variable does not seem to be used by the driver correctly. In `connect` of `tds.go`, `p.dial_timeout` is used to set the context timeout (https://github.com/denisenkom/go-mssqldb/blob/master/tds.go#L723). In `getInstances` of `tds.go`, the timeout value of the same context is overwritten by a hard coded value of 5 seconds (https://github.com/denisenkom/go-mssqldb/blob/master/tds.go#L52). The deadline of the `conn` object should also be set to the remainder of the context instead of the hard coded 5 seconds value.
Fix for #522 .

Use the dial timeout variable

---

conn_str.go
conn_str_test.go
tds.go

Existing implementation sets default port to 1433 right during connection string parsing. I have removed setting to default port in order for being able to determine if the port was specified.
Now, instance resolution takes place only if the default port is not set. At each place connection parameter's port is used a port resolution is applied. If it is 0 then default port is applied.
P.S. Didn't know why SPN is currently required. Didn't find where it is used.

Fixing instance resolution if both instance and port are set in connection string.

---

mssql.go

Currently, `go vet` reports:
```
❯ go vet 2>&1 | grep mssql.go
./mssql.go:596:2: the cancel function is not used on all paths (possible context leak)
./mssql.go:616:5: this return statement may be reached without using the cancel var defined on line 596
```
This PR fixes these.

make sure to call cancel func

---

mssql.go

Addresses issue #526 . 
@jackwakefield, if you had a fix in the works let me know and I'll remove this PR.
Tested timeout using the query `select * from sys.dm_qn_subscriptions` and found that the timeout value was equal to the value set by the driver.

change query notification timeout from seconds to milliseconds

---

mssql.go

Fixes issue #536
The issue occurs when [sql.DB#BeginTx(context.Context, *sql.TxOptions)](https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1723) is called after SQL server connection is closed by, for example, shutting down SQL server by stopping its Docker container. See [sevasm/go-mssqldb-panic](https://github.com/sevasm/go-mssqldb-panic) for an example program that can reproduce the issue reliably.
The issue cannot be reproduced by closing the underlying transport of the connection as is done in a number of tests, e.g. [TestCommitTranError (conn.sess.buf.transport.Close())](https://github.com/denisenkom/go-mssqldb/blob/master/queries_test.go#L1101).
After closing the underlying transport and calling [sql.DB#BeginTx(context.Context, …

Issue #536 - prevent panic when starting a transaction after making connection and shutting down SQL server 

---

tvp_go19_db_test.go

The TestTVP and TestTVP_WithTag functions in tvp_go19_db_test.go use time.Now to generate test data for SQL Server datetime2 values that they compares after round-tripping through the test database. The problem with this is that Go's time type allows resolution down to 1 nsec, while datetime2 allows a maximum of 100 nsec resolution (7 digits of precision). Depending on the system clock, the time.Now test values could have higher precision than datetime2 supports, causing truncation and subsequent test failure.
I encountered this problem on my machine, and I see that sysadmind reports the same in his recent [pull request](https://codecov.io/gh/denisenkom/go-mssqldb/pull/584?src=pr&el=desc).
This pull request substitutes a static time value with 100 nsec resolution for the time.Now values …

Prevent TVP tests from failing due to system clock precision

---

appveyor.yml
queries_test.go

- add SQL2017 and SQL2019
- add Go 1.12, 1.13, and 1.14
Tests fail with Go 1.12 or later, but it is not due to this pull request.
`go test` detects data race.
https://ci.appveyor.com/project/shogo82148/go-mssqldb/builds/34908425/job/vxdgjcwfpenv6889
```
Build started
git clone -q --branch=go1.15-is-released https://github.com/shogo82148/go-mssqldb.git c:\gopath\src\github.com\denisenkom\go-mssqldb
git checkout -qf de1c72fd830286d2a3f7aa18ce7fea11e21f4212
Running Install scripts
set GOROOT=c:\go%GOVERSION%
set PATH=%GOPATH%\bin;%GOROOT%\bin;%PATH%
go version
go version go1.14.6 windows/amd64
go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\appveyor\AppData\Local\go-build
set GOENV=C:\Users\appveyor\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set …
```

update the build matrix

---

.github/workflows/reviewdog.yml
.golangci.yml

introduce GitHub Action: Run golangci-lint with reviewdog https://github.com/reviewdog/action-golangci-lint
I found `(*Rows).Close` are not called correctly (#600 fixes it).
These tool help you from making such a mistake before it happens.

introduce reviewdog

---

bulkcopy_test.go
datetimeoffset_example_test.go
lastinsertid_example_test.go
mssql.go
queries_go110_test.go
queries_go19_test.go
queries_test.go
tds.go
tds_test.go
token.go
tvp_go19_db_test.go

This pull request may fixes races reported by https://github.com/denisenkom/go-mssqldb/pull/596#issue-475458766
It looks that [processResponse](https://github.com/denisenkom/go-mssqldb/blob/1e08a3fab20416d36c5fe538e75939710003f611/token.go#L788) and [processSingleResponse](https://github.com/denisenkom/go-mssqldb/blob/1e08a3fab20416d36c5fe538e75939710003f611/token.go#L558) are not safe to call concurrently.
So, callers of these functions must wait until the functions finish by making sure channels are closed.
In addition, we should call `(*Rows).Close` correctly, because `(*Rows).Close` makes sure the channels created by (*Stmt).Query are closed.

Make sure channels are closed and close Rows and Stmt

---

buf.go
tds_test.go

We noticed that when connecting to many databases, the amount of memory being utilized by the `newTdsBuffer()` func was rather significant, especially in comparison to the business logic that utilized the connections. I was able to use pprof to figure out that the `newTdsBuffer()` func was the source of the memory utilization and that these 2 buffers get initialized to a fairly large size. This reduces the size of the buffers to match the packetsize, significantly reducing the amount of memory used for the buffers in the majority use case.
I added a benchmark in order to help illustrate the difference in utilization before and after. Below are 
the results on my machine before and after this change. In the default case (packetSize = 4096) this resulted in a 64% reduction in bytes …

Reduce tds buffer size to match packetsize

---

appveyor.yml
net.go
net_go116_test.go
queries_test.go

This PR should workaround the issues regarding to the tls changes in Go 1.16.
**This is by no means a proper fix**
I do not have enough knowledge about the foundation of the tls package. I can only confirm that the changes fixed my issues.

Workaround for Go 1.16

---

README.md

generated by https://pkg.go.dev/badge/
ref. Redirecting godoc.org requests to pkg.go.dev
https://blog.golang.org/godoc.org-redirect

migrate the godoc.org badge to pkg.go.dev

---

.gitignore
.pipelines/README.md
.pipelines/TestSql2017.yml
README.md
conn_str.go
conn_str_test.go
doc/how-to-use-table-valued-parameters.md
queries_go19_test.go
tds_test.go

Per request in #645 this change expands the set of keys usable in the ADO-style connection string to include `application name` as well as synonyms for `database` and `user id` and `server`.
The scope of the PR is a bit bigger than that because it includes:
1. A simple Azure Devops pipeline yml I used in my fork for testing, 
2. A small bug fix in a test to match case on a variable. The test was failing when run against a case sensitive collation
3. Some formatting fixes to md files to enable `go` syntax highlighting and satisfy vs code's go linter.
Feel free to cherry pick those out or I can figure out how to do it.

Add synonyms for ADO-style connection string parameters

---

tds.go

Fixes #653. 
Login errors don't get returned as `mssql.Error`. Instead they are returned as plain old `error`. This is due to a snippet in [tds.go](https://github.com/denisenkom/go-mssqldb/blob/master/tds.go#L1208) that removes the typing of the error message in order to preface the error with `"login error: "`. This PR adjusts that snippet to return `mssql.Error` while still maintaining the `"login error: "` prefix.

Fix issue where login errors are not returned as mssql.Error

---

mssql.go

Hello! 
I'm having the same `panic: driver.ErrBadConn in checkBadConn. This should not happen` as #536, except with `Stmt.exec`.
This is the same fix as #583.

Don't check Stmt.processExec errors twice

---

bulkcopy.go
bulkcopy_test.go

Allow insert from int64 to varchar and nvarchar in bulkcopy

bulkcopy: allow int64 to varchar and nvarchar

---

bulkcopy.go
mssql.go
mssql_go19.go
mssql_perf_test.go
queries_go19_test.go
tds.go
tds_test.go
token.go

Fixes #654.
- Add a new test to demonstrate that `returnStatus` is not cleared at all between two queries on the same connection.
- Move `returnStatus` to the same place as `outs` since they have the same scope, and a very similar usage.
- Gather `returnStatus` and `outs` into a struct, because we have to pass both to several functions, and also because I plan to propose a third member. `outs` becomes `outs.params`.
- Ensure `outs` is cleared even when we get an early error.

Clear returnStatus between two queries on the same connection

---

mssql.go

This is a case where one could say "if it ain't broke don't fix it".
I noticed stored procedures are executed in SQL batches instead of RPC if we don't pass parameters.
This is a little inconsistent, but there doesn't seem to be a significant difference.
In both cases, SQL Server returns an error if you pass too many arguments.
I can't think of another difference.
Please note that a stored procedure can have default parameters, which means one could call it with or without arguments.
This means that `db.Exec("my_proc")` and `db.Exec("my_proc", 42)` both work, but one is an RPC while the other one is an SQL batch, until this PR is merged.

Use RPC to execute a stored proc without parameters

---

queries_test.go
tds.go
tds_test.go
token.go

I saw test failures per issue #679 due to higher latency connections to my servers. The error should have been `DeadlineExceeded` but it was getting a spurious `did not get cancellation confirmation`.
The fix is to instruct the reader not to send attention during `ctx->done()` handling during the login processing.
Along the way I fixed the set language test that was failing on my server, which has a case sensitive collation.

Don't send attention during login

---

bulkcopy.go
error.go
error_test.go
msdsn/conn_str.go
msdsn/conn_str_go118.go
msdsn/conn_str_go118pre.go
msdsn/conn_str_test.go
mssql.go
mssql_go118.go
mssql_go118pre.go
mssql_test.go
queries_test.go
token.go

This pull request resolves #586. It is the result of collaboration by @kardianos, @tc-hib, @shueybubbles, and myself.
First, it adds an optional parameter named "disableretry" to the connection string. When set to "true", this parameter configures go-mssqldb's retry policy to match that requested in issue #275: failed queries immediately return a detailed error.  When set to "false", this parameter configures the retry policy to match that requested in issue #586: failed queries are automatically retried as per the standard library's database/sql retry logic.
For versions of Go less than 1.18, the default value for "disableretry" is "true", maintaining backwards compatibility.
Second, starting with Go 1.18 when (we hope) kardianos' change proposal [333949 …

Automatic Bad Connection Retry

---

mssql.go
mssql_test.go
tvp_go19_test.go

This PR fixes `isProc` which detects if a string contains nothing but an object name.
It may still be a long way from the real lexer.
I had to fix 2 tests:
- Proc name `"[proc\n1]"` is valid
- Table type name `"123.[Test]"` is not

Support a few other cases in isProc

---

tds.go

Fixes #482 
`p.TLSConfig` here is a pointer back to the original config, so we shouldn't overwrite its contents in this retry loop. Otherwise the `TLSConfig.ServerName` doesn't match `p.Host` on new connections for the first `Handshake` call.
@kardianos  once this is in can you create a 0.10.1 release for the AKS team at Microsoft to consume?
They want to pick up an official release with the fixes for bad connection marking.

keep tls config in sync with msdsn host

---

bad_server_test.go
bulkcopy.go
bulkcopy_test.go
log.go
log_go113_test.go
log_go113pre_test.go
log_test.go
msdsn/conn_str.go
mssql.go
mssql_perf_test.go
mssql_test.go
net_go116_test.go
queries_go110_test.go
queries_go110pre_test.go
queries_go19_test.go
queries_test.go
tds.go
tds_go110_test.go
tds_go110pre_test.go
tds_login_test.go
tds_test.go
token.go
tvp_go19_db_test.go

This pull request resolves #680 and adds a ContextLogger interface to improve the capabilities of the existing Logger interface. Compared to the Logger interface, ContextLogger:
1. Supplies the context to the Log function, allowing the developer to include things such as trace IDs in the logged messages
2. Supplies the category of the message being logged, allowing the developer to handle different classes of messages differently (e.g. send debug messages to a file while sending error messages to a system log)
3. Allows the developer to decide whether or not to include prefixes such as "ERROR:" in the messages
4. Adds a LogRetries category that allows the developer to log errors that would otherwise be hidden by successful retries.
This pull request maintains the existing Logger for …

Context Logger

---

tds.go

For Microsoft SQL Host could take form [server]\\[instance]. Without this fix LookupIP will fail in this scenario.

Fix an issue where Host is named instance name

---

tds.go

Although this is not explicitly specified drivers do include Instance into LOGIN7 ServerName field and AzureSQL relies on this in certain scenarios (if not included connections will fail).
This is discovered during the follow-up discussion related to #707

Fix: Include Instance into LOGIN7 ServerName field

---

tvp_go19.go
tvp_go19_db_test.go

Data type 0x26 has an invalid data length or metadata length.
#713

Fix bug with unsighted types

---

error.go
queries_go19_test.go
token.go

Fixes #745.
Caused by https://github.com/golang-sql/sqlexp/commit/d42ba59f5c11011b1df5abc536ee75821c22bdac.

Implement stringer interface
